#!/bin/bash

echo "Song: "

read songUrl

yt-dlp -x $songUrl \
 --extract-audio \
 --audio-format mp3 \
 --audio-quality 128K \
 --add-metadata \
 --embed-thumbnail \
 --ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
