#!/bin/bash

if [ -z $1 ]
then
  echo "Song: "
  read songUrl
else
  songUrl=$1
fi

yt-dlp -x $songUrl \
 --extract-audio \
 --audio-format mp3 \
 --audio-quality 128K \
 --add-metadata \
 --embed-thumbnail \
 --ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
